# .gitstream/config.yml

manifest:
  version: 1.0

automations:
  linearb_ai_review:
    if:
      - {{ pr.author | match(list=['github-actions', 'dependabot', '[bot]']) | nope }}
    run:
      - action: code-review@v1

  linearb_ai_description:
    if:
      - {{ pr.author | match(list=['github-actions', 'dependabot', '[bot]']) | nope }}
    run:
      - action: describe-changes@v1
